package br.com.graphene.copom.sampledynamo.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "copom-comunicados-app-customers")
public class Customer {
  private String id;
  private String name;
  private String cpf;

  public Customer() {
  }

  public Customer(String name, String cpf) {
    this.name = name;
    this.cpf = cpf;
  }

  @DynamoDBHashKey
  @DynamoDBAutoGeneratedKey
  public String getId() {
    return id;
  }

  @DynamoDBAttribute
  public String getName() {
    return name;
  }

  @DynamoDBAttribute
  public String getCpf() {
    return cpf;
  }

  public void setId(String id) {
    this.id = id;
  }

  public void setName(String name) {
    this.name = name;
  }

  public void setCpf(String cpf) {
    this.cpf = cpf;
  }
}

